// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeSjq9ppwI0lliYLjco0yOePnw4U2iIOQ',
    appId: '1:399218897382:android:abe6bc8904c0ff0835e627',
    messagingSenderId: '399218897382',
    projectId: 'food-67ca3',
    storageBucket: 'food-67ca3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAxKl_fjUu_SA-8LtNmPc3_2ndXwLI4TA',
    appId: '1:399218897382:ios:c648e4d13f268f7b35e627',
    messagingSenderId: '399218897382',
    projectId: 'food-67ca3',
    storageBucket: 'food-67ca3.firebasestorage.app',
    iosBundleId: 'com.example.foodBridge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHezqHDRzVW91rC79ybMgRC9ErNPFdceM',
    appId: '1:399218897382:web:482ab41d02ef912335e627',
    messagingSenderId: '399218897382',
    projectId: 'food-67ca3',
    authDomain: 'food-67ca3.firebaseapp.com',
    storageBucket: 'food-67ca3.firebasestorage.app',
    measurementId: 'G-8S0Q2120HX',
  );

}